### ISSUE TITLE
Jobseeker Education: Not loading college if different selected and saved

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#156] opened 2024-11-27 20:12 UTC
http://localhost:3000/edit-profile/jobseeker/education
![Image](https://github.com/user-attachments/assets/afee2bc6-75b2-4711-966d-f8b466eab234)

If college is saved and then a different college is selected and saved. It displays the original college that was selected but confirmed the new college is being stored in the database.

**Comment by cfa-jonathan** [comment] 2024-12-03 03:49
This is resolved in https://dev.azure.com/CFA1/Career%20Services/_git/CoalitionWebsite/pullrequest/142

With additional fixes related to the same root cause, and also changed some required denotations.

**Closed as completed** 2024-12-03 05:30 UTC
