### ISSUE TITLE
Skills 

### ISSUE THREAD

**Issue by dharam9610** [Computing-For-All/nextjs-issue-tracker#114] opened 2024-11-07 19:07 UTC
### Duplicate Check

- [X] I have searched for and didn't find any pre existing issue tracking this

### Issue Type

Not sure

### Issue Description

Skills are not displayed on this page

### URL of the Page

https://www.watechwfcoalition.org/services/jobseekers/9ad6ab07-73ca-4aee-b1b4-3d722856374d

### Git commit hash shown on the site

a95009e

### Steps to Reproduce

Enter 5 skills when creating the profile. After profile creation is complete, check if the skills display on this summary page.

### Expected Behavior

Skills should display on this page

### Additional Context

Browser: Safari
OS: Mac Sequoia 15.0

### Recommended Priority Level

Medium

**Comment by theGaryLarson** [comment] 2024-11-09 19:27
Dharam demonstrated to reduplicate and worked as expected. This is on Mac some testing may be necessary.

**Comment by rorosaurus** [comment] 2024-11-12 22:33
Unable to repro on Mac 14.6.1. updating to 15.

**Comment by rorosaurus** [comment] 2024-11-12 23:33
Still unable to reproduce! Closing for now.

**Closed as completed by rorosaurus** 2024-11-12 23:33 UTC
Labels: uat, jobseeker
